### ISSUE TITLE
Routes generator doesn't support associations where the class name isn't the same as the association name

### ISSUE THREAD

**Issue by tspacek** [Papercloud/restkit_generators#26]
Because it's grabbing the associations from the serialiser, and the serialiser doesn't seem to have that info without an instance of the object getting serialised. This bit might require a rethink.

**Comment by antonivanopoulos** [comment]
@tspacek 
Instead of something like:

```
serializer._associations.keys.map(&:to_s).map(&:pluralize)
```

Could use a similar approach to the model generator:

```
serializer.model_class.reflect_on_all_associations # etc etc
```

Ending up with a list of association objects, including the class name, macro and options (among other things), and we can do whatever from there.

Thoughts?

**Comment by antonivanopoulos** [comment]
Should also clarify that we would filter to still only grab the associations present in the serialiser.

**Comment by tspacek** [comment]
Good thinking
