### ISSUE TITLE
Routes generator needs a way to specify model name

### ISSUE THREAD

**Issue by tspacek** [Papercloud/restkit_generators#32]
If I run

```
GEN=1 rails g rest_kit:route "api_v3_template_templates" --ios-path=../iCommercialAgentiOS --serializer="Template::TemplateSerializer"
```

I get 

```
/Users/tomas/Work/Papercloud/restkit_generators/lib/restkit_generators/ios/model.rb:42:in `associations': undefined method `reflect_on_all_associations' for Template:Module (NoMethodError)
    from /Users/tomas/Work/Papercloud/restkit_generators/lib/generators/rest_kit/route/route_generator.rb:108:in `associations'
```

Because it can't find my model `Template::Template`

**Comment by markst** [comment]
:+1:

**Comment by antonivanopoulos** [comment]
@tspacek Ah, nice pick up, I'll add it in. :+1: 

I think `model_name = route.name.split("_").last` causes a few issues when determining the model from the route, as it doesn't allow for models made up of multiple words either (i.e. `api_v1_my_customer_account` just infers the model as `Account`). Not sure if the model flag would be the ideal solution for that scenario, too.
