### ISSUE TITLE
[ROUTES] Stripping out the namespace doesn't work as intended for member actions

### ISSUE THREAD

**Issue by antonivanopoulos** [Papercloud/restkit_generators#37]
@tspacek This one's more of a question around how the `strip_namespace` CLI option should work, given that the default is `api`, and I generate the `api_jobs` route, I'll end up with a nice new `RKObjectManager+JobsRoute` category, which is all good.

But if I have a member action on the `jobs resource`, let's say `deliver`, the named route is `deliver_api_job`, so if I generate that named route, we end up with `RKObjectManager+DeliverApiJobRoute` category.

Should we maybe gsub the namespace out instead of ditching it if it's the prefix? Or maybe, if the prefix matches the controller action, we break that off, do our prefix search, ditch the namespace if it's the new prefix, then merge the old prefix back on?

**Comment by tspacek** [comment]
Have you resolved this already?

**Comment by antonivanopoulos** [comment]
@tspacek Yeah, all good :+1:
