### ISSUE TITLE
Incorrect tab indentation.

### ISSUE THREAD

**Issue by markst** [Papercloud/restkit_generators#40]
All tab indentations are two spaces rather than a tab or four character. 

![image](https://cloud.githubusercontent.com/assets/274318/8476103/c1afe988-20b5-11e5-99b6-ace8ce3a0af8.png)

**Comment by tspacek** [comment]
Please no tab characters: they suck if diff people have them set to diff
widths. Four spaces would be sensible.

**Comment by antonivanopoulos** [comment]
Yeah cool, easy one, my sublime is just set two 2 spaces per tab.
